// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nav': string;
  'nav--colour-scheme': string;
  'nav--goto-repo': string;
  'nav--how-to-host': string;
  'nav--how-to-play': string;
  'nav--play-offline': string;
  'nav--play-online': string;
  'nav--report-issue': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
