// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pause-overlay': string;
  'scroll-outer': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
