// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls-bar': string;
  'grid-wrapper': string;
  'players-bar': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
