// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-wrapper': string;
  'group-name': string;
  'host-url': string;
  'passphrase': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
