// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lang-sel': string;
  'lang-weight-exagg': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
