// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'opt': string;
  'opt-label': string;
  'opt-label--author': string;
  'opt-label--title': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
