// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'opt': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
