// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anim-frames-player__on-move': string;
  'downed-overlay': string;
  'face': string;
  'spotlight-long': string;
  'spotlight-short': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
