// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'char': string;
  'pointer-hitbox': string;
  'seq': string;
  'this': string;
}
export const cssExports: CssExports;
export default cssExports;
