// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_player__downed-overlay': string;
}
export const cssExports: CssExports;
export default cssExports;
